name: Rust

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
      # run: cargo build --verbose
    # - name: Run package tests
    #   run: cargo test --package package
    - name: Full Test
      run: cargo test --all --locked
      # run: cargo test --all --verbose --locked
